"""
Django settings for konfigurasi_proyek project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kt662x-vi#j$dvea$%dnjuf4)4$n)him*sgh1w*=1*1&&2arq0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.8']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'analisis',
    
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'konfigurasi_proyek.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'analisis.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'konfigurasi_proyek.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# konfigurasi_proyek/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'analisis',         # Nama database yang Anda buat
        'USER': 'root',                 # User database Anda (default XAMPP/Laragon)
        'PASSWORD': '',                 # Password database Anda (kosongkan jika tidak ada)
        'HOST': 'localhost',            # Atau 'localhost'
        'PORT': '3306',                 # Port default MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# URL tujuan jika pengguna mencoba mengakses halaman yang butuh login,
# tapi mereka belum login. Kita arahkan ke URL dengan nama 'login'.
LOGIN_URL = 'login'

# URL tujuan SETELAH pengguna berhasil login.
# Kita arahkan ke URL dengan nama 'home' (yang merujuk ke '/home/').
LOGIN_REDIRECT_URL = 'home'

# URL tujuan SETELAH pengguna logout.
# Kita kembalikan ke halaman login.
LOGOUT_REDIRECT_URL = 'login'


STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Testing
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# # Production
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'emailanda@gmail.com'  # <-- Ganti dengan email Anda
# EMAIL_HOST_PASSWORD = 'host anda'

# tutor untuk dapat host password
# 1. Aktifkan Verifikasi 2 Langkah di Akun Google Anda.
# 2. Buka halaman Sandi Aplikasi.
# 3. Buat sandi baru untuk aplikasi (beri nama "Django Project" atau semacamnya).
# 4. Google akan memberi Anda 16 karakter password. Salin password ini.
# 5. Gunakan password 16 karakter tersebut di settings.py Anda untuk EMAIL_HOST_PASSWORD.


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Kita akan menggunakan TokenAuthentication untuk mobile app
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Secara default, semua endpoint butuh login
        'rest_framework.permissions.IsAuthenticated',
    ],
}
