# Generated by Django 5.2.6 on 2025-09-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataKomoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komoditas', models.CharField(max_length=100)),
                ('nama_pasar', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HasilAnalisis',
            fields=[
                ('nama_komoditas', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('klaster_json', models.JSONField(null=True)),
                ('srs_json', models.JSONField(null=True)),
                ('standar_deviasi', models.FloatField(null=True)),
                ('varians', models.FloatField(null=True)),
                ('terakhir_diproses', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
