# Generated by Django 5.2.6 on 2025-09-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakomoditas',
            name='blok_pasar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datakomoditas',
            name='nama_pedagang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datakomoditas',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
