# Generated by Django 5.2.6 on 2025-09-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_datakomoditas_blok_pasar_datakomoditas_nama_pedagang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakomoditas',
            name='harga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datakomoditas',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
