# Generated by Django 5.2.6 on 2025-10-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_alter_datakomoditas_harga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilanalisis',
            name='standar_deviasi',
        ),
        migrations.RemoveField(
            model_name='hasilanalisis',
            name='terakhir_diproses',
        ),
        migrations.RemoveField(
            model_name='hasilanalisis',
            name='varians',
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='standar_deviasi_populasi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='standar_deviasi_sampel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='varians_populasi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='varians_sampel',
            field=models.FloatField(default=0),
        ),
    ]
