# Generated by Django 5.2.6 on 2025-10-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_remove_hasilanalisis_standar_deviasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Beras, Cabai, Daging Sapi', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Komoditas',
            },
        ),
        migrations.CreateModel(
            name='Pasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasar', models.CharField(max_length=255, unique=True)),
                ('alamat', models.TextField()),
                ('latitude', models.FloatField(help_text='Koordinat Latitude (contoh: -6.273105)')),
                ('longitude', models.FloatField(help_text='Koordinat Longitude (contoh: 106.865303)')),
                ('komoditas', models.ManyToManyField(related_name='pasar_terkait', to='analisis.komoditas')),
            ],
            options={
                'verbose_name_plural': 'Pasar',
            },
        ),
    ]
