# Generated by Django 5.2.6 on 2026-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_remove_hasilanalisis_standar_deviasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilanalisis',
            name='standar_deviasi_kmeans',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hasilanalisis',
            name='varians_kmeans',
            field=models.FloatField(default=0),
        ),
    ]
